### PR TITLE
Stand alone parameters schema

### PR DESCRIPTION
**Pull request by ewels**
First attempt at restructuring the `parameters.settings.json` to be a stand-alone JSON Schema file.

See discussion in https://github.com/nextflow-io/nextflow/issues/866

I recommend viewing the PR with whitespace changes ignored 👍

### CODE REVIEW

**Comment by ewels** [comment]
Failing tests are unrelated to this PR and are due to lint errors from an updated version of tools. The pipeline needs to be synced with the new template, then they will pass.

**Comment by ewels** [comment]
Sure! I made a start with that here, but no PR yet: https://github.com/ewels/nf-core-tools/blob/stand-alone-schema/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/parameters.settings.json

I wondered if I would be better off working on the `tools` code first / some kind of website tool to aid creating these files. For example: https://bjdash.github.io/JSON-Schema-Builder/ - could work great in combination with a cli tool to make a skeleton file based on the params found from the pipeline. Needs ability to drag and drop order etc though.

**Comment by apeltzer** [comment]
This is super ancient now, so closing this :)

**Comment by ewels** [comment]
Yeah - in principle the new schema looks kind of the same, but better to generate it using `nf-core schema build` instead.

**Pull request closed without merging**
