### PR TITLE
Parse parameters.json and use it in the help message

### PR DESCRIPTION
**Pull request by sven1103**

### CODE REVIEW

**Comment by ewels** [comment]
Awesome! Whats does the stdout look like? Can we see an example? 😀

**Comment by sven1103** [comment]
```
u-082-c119:hlatyping sven1103$ nextflow run . --help
N E X T F L O W  ~  version 18.10.1
Launching `./main.nf` [astonishing_hypatia] - revision: 9aa3f4b682
          --bam              Hlatyping will extract the reads and remap.
          --singleEnd        Flag if input data is of type singleEnd.
          --seqtype          Tells hlatyping if input is of type DNA or RNA.
          --solver           Selects an IP solver alghorithm for hlatyping.
          --enumerations     Shows additional n-1 suboptimal solutions from OptiType.
          --beta             Shows additional n-1 suboptimal solutions from OptiType-
          --prefix           Adds a string prefix to the output files.
          --reads            HLA typing workflow input data.
          --index            Yara HLA dna reference index location.

```

No grouping yet, this will come :)

**Comment by sven1103** [comment]
Can also print ranges/enumerations if available

**Comment by ewels** [comment]
Would be great if non-boolean-flag options could show the value that they expect, eg:

```
Options:

      --bam              Hlatyping will extract the reads and remap.
      --singleEnd        Flag if input data is of type singleEnd.
      --seqtype [dna/rna]  Tells hlatyping if input is of type DNA or RNA.
                           Default: dna
      --solver [option 1/option2/option3/option4]
                            Selects an IP solver alghorithm for hlatyping.
      --enumerations [int]     Shows additional n-1 suboptimal solutions from OptiType.
      --beta             Shows additional n-1 suboptimal solutions from OptiType-
      --prefix [str]    Adds a string prefix to the output files.
                        Default: None
      --reads [path]    HLA typing workflow input data..
                        Default: data/*_{1,2}.fastq.gz
      --index [path]            Yara HLA dna reference index location.
```

Messy crappy example because I'm in a rush, but hopefully that makes sense 😅 I'm thinking like the behaviour for the `click` help messages on the `nf-core` python package:

```
Usage: nf-core create [OPTIONS]

  Create a new pipeline using the template

Options:
  -n, --name TEXT         The name of your new pipeline  [required]
  -d, --description TEXT  A short description of your pipeline  [required]
  -a, --author TEXT       Name of the main author(s)  [required]
  --new-version TEXT      The initial version number to use
  --no-git                Do not initialise pipeline as new git repository
  -f, --force             Overwrite output directory if it already exists
  -o, --outdir TEXT       Output directory for new pipeline (default: pipeline
                          name)
  --help                  Show this message and exit.
```

```
Usage: nf-core list [OPTIONS] <filter keywords>

  List nf-core pipelines with local info

Options:
  -s, --sort [release|pulled|name|stars]
                                  How to sort listed pipelines
  --json                          Print full output as JSON
  --help                          Show this message and exit.
```

**Comment by KochTobi** [comment]
> Would be great if non-boolean-flag options could show the value that they expect, eg:
> 
> ```
> Options:
> 
>       --bam              Hlatyping will extract the reads and remap.
>       --singleEnd        Flag if input data is of type singleEnd.
>       --seqtype [dna/rna]  Tells hlatyping if input is of type DNA or RNA.
>                            Default: dna
>       --solver [option 1/option2/option3/option4]
>                             Selects an IP solver alghorithm for hlatyping.
>       --enumerations [int]     Shows additional n-1 suboptimal solutions from OptiType.
>       --beta             Shows additional n-1 suboptimal solutions from OptiType-
>       --prefix [str]    Adds a string prefix to the output files.
>                         Default: None
>       --reads [path]    HLA typing workflow input data..
>                         Default: data/*_{1,2}.fastq.gz
>       --index [path]            Yara HLA dna reference index location.
> ```
> 
> Messy crappy example because I'm in a rush, but hopefully that makes sense sweat_smile I'm thinking like the behaviour for the `click` help messages on the `nf-core` python package:
> 
> ```
> Usage: nf-core create [OPTIONS]
> 
>   Create a new pipeline using the template
> 
> Options:
>   -n, --name TEXT         The name of your new pipeline  [required]
>   -d, --description TEXT  A short description of your pipeline  [required]
>   -a, --author TEXT       Name of the main author(s)  [required]
>   --new-version TEXT      The initial version number to use
>   --no-git                Do not initialise pipeline as new git repository
>   -f, --force             Overwrite output directory if it already exists
>   -o, --outdir TEXT       Output directory for new pipeline (default: pipeline
>                           name)
>   --help                  Show this message and exit.
> ```
> 
> ```
> Usage: nf-core list [OPTIONS] <filter keywords>
> 
>   List nf-core pipelines with local info
> 
> Options:
>   -s, --sort [release|pulled|name|stars]
>                                   How to sort listed pipelines
>   --json                          Print full output as JSON
>   --help                          Show this message and exit.
> ```

yes I will implement that right away

**Comment by KochTobi** [comment]
Next step grouping by `group` field and sorting by name.
```
N E X T F L O W  ~  version 18.10.1
Launching `../hlatyping/main.nf` [exotic_montalcini] - revision: 50057f072b

=========================================
 nf-core/hlatyping v1.1.4
=========================================
Usage:

The typical command for running the pipeline is as follows:

nextflow run nf-core/hlatyping --reads '*_R{1,2}.fastq.gz' -profile docker

Options:

    --bam                           Hlatyping will extract the reads and remap.
    --singleEnd                     Flag if input data is of type singleEnd.
    --seqtype       [dna, rna]      Tells hlatyping if input is of type DNA or RNA.
    --solver        [glpk, cbc]     Selects an IP solver alghorithm for hlatyping.
    --enumerations  [1, 150]        Shows additional n-1 suboptimal solutions from OptiType.
    --beta          [0.0, 0.1]      Shows additional n-1 suboptimal solutions from OptiType-
    --prefix        string          Adds a string prefix to the output files.
    --reads         string          HLA typing workflow input data.
    --index         string          Yara HLA dna reference index location.
```

**Comment by ewels** [comment]
Awesome! When can we get it in the `tools` template?? 😀

**Pull request merged**
