### PR TITLE
Fix - min Version for NF >0.30.0

### PR DESCRIPTION
**Pull request by apeltzer**
Also adding a configuration file for Singularity

### CODE REVIEW

**Comment by ewels** [comment]
Version 0.30.0 had some weird errors with params parsing. I've skipped over setting this as the minimum version for other pipelines as the tests did weird things. May be worth setting to at least 0.30.1 for this reason..

**Comment by ewels** [comment]
This also needs updating in `.travis.yml` too..

**Comment by pditommaso** [comment]
Use the latest 0.30.2.

**Comment by apeltzer** [comment]
Will do now!

**Comment by apeltzer** [comment]
This should do now :-) Choo Choo commits from the train :-)

**Comment by ewels** [comment]
Still needs updating in `.travis.yml` 😉

**Comment by apeltzer** [comment]
Goddamn Jetlag - now its there!

**Pull request merged**
