### PR TITLE
Fix the input paramater and missing parameters in the doc

### PR DESCRIPTION
**Pull request by nvk747**
This pull request was created to replace --reads with --input. Adding missing parameter options for TOC in  README.md

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).
## PR checklist
 - [ ] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/hlatyping branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/hlatyping)
 - [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [ ] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [* ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/hlatyping/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by christopher-mohr** [comment]
@nvk747 thanks for your work on this! We still have to adapt the tests to these changes. Therefore the test configs (`test.config`,  `test_fastq.config` and `test_rna.config`) have to be adapted in the folder `conf`. Would you like to do that?

**Comment by nvk747** [comment]
@christopher-mohr , Thanks for putting the msg..hope my corrections are good to put... I can change the test configs as per our changes in the main.nf.

**Comment by christopher-mohr** [comment]
> @christopher-mohr , Thanks for putting the msg..hope my corrections are good to put... I can change the test configs as per our changes in the main.nf.

Thanks! Just add the changes to this PR.

**Comment by christopher-mohr** [comment]
Resolved the conflicts. I think this is good to be merged now. Pipeline schema will be fixed with a separate PR.

**Pull request merged**
