### PR TITLE
Add example citation file format

### PR DESCRIPTION
**Pull request by sven1103**
Creates an example CFF for nf-core/hlatyping

addresses https://github.com/nf-core/tools/issues/361

## PR checklist
 - [ ] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/hlatyping branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/hlatyping)
 - [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [ ] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/hlatyping/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by ewels** [comment]
Minor thing, but would be nice to add to the `.gitattributes` file for some syntax highlighting 🙄 

See https://github.com/nf-core/rnaseq/blob/master/.gitattributes for an example:

```
*.cff linguist-language=yaml
```

**Comment by ewels** [comment]
Looking good! I thought that this was more about citing the tools within the pipeline though? We can automate everything written in this pretty easily so if it's just this then I'd be more inclined to make this a feature of `nf-core cite` instead of bundling a file that needs maintaining in the repos..

**Comment by apeltzer** [comment]
I thought as well that its more about the citation of the tools in the pipeline rather than the actual pipeline (as we have a statement or thought about having a nag in the template for all pipelines?).

**Comment by sven1103** [comment]
Hm, no as i have written here https://github.com/nf-core/tools/issues/361, it is about a standard citation file format for software, a work out of the Sustainable Software Institute (https://www.software.ac.uk/). Think about automated reference manager import. 

Read more about it here: https://genr.eu/wp/software-citation-for-humans/

Happy to discuss this further of course

**Comment by sven1103** [comment]
Think about all the other standardized files in a Software Repo: README, LICENSE, CHANGELOG, ... it is just another standard file where you look at, in this case, when a human or a machine wants to know how to cite a software. That is it. Maintenance is no strong argument for me honestly, as you have this information somewhere hidden in the README anyway. So instead you would put this information there. But standardized ;)

**Comment by ewels** [comment]
Yeah, I know nf-core/tools#361, my understanding throughout that issue thread was also that the CFF file would primarily be used to cite the software within the pipeline (hence my [comment](https://github.com/nf-core/tools/issues/361#issuecomment-515737558) and link to the other issue thread). The included software won't change much so is easy to maintain. What you have here is quite different though - there are currently 23 collaborators on the rnaseq pipeline, it would be quite a hassle to check and collect those details for every person and check on each release (most people don't have affiliation etc listed on GitHub).

I think the file is still a good idea, can we include this into the Zenodo release automation system? Then we could just scrape all of this using the GitHub API. No reason not to add it manually here first though I guess.

If this doesn't contain the included software references, then we should go back to that discussion again and figure out how to best do that :)

**Comment by sven1103** [comment]
I think we have to agree on what we define as an author for a pipeline. How is an contributor different than an author in terms of software development. And if we make a difference, what are the metrics that define this? 

What you motivate in https://github.com/nf-core/tools/issues/236 is a different context for me however. This is not about proper citation, but a materials section including the tools, right?

**Comment by ewels** [comment]
> This is not about proper citation, but a materials section including the tools, right?

Yes, exactly. But if someone uses the pipeline in a research paper, I think it's right that they should cite both the pipeline and the tools that the pipeline executes. So for me the two go together.

But I don't think that there's any problem here - this just isn't what I thought it was 😅 But I guess we can have both? CFF for the pipeline and `.bibtex` etc for the pipeline and included tools?

**Comment by sven1103** [comment]
Whatever fits the purpose of integrating citation managers. If there are no integrations for CFF now, then it is maybe too early to use it in nf-core? However if nobody uses it, the how will citation managers provide support. Henn egg problem. I am also open for alternatives, as long as it is good practise :)

**Comment by ewels** [comment]
Here are some to choose from 😓 

image

I think BibTeX is the best if we're going for one format.

But yeah, I have no problem with having a CFF file as well. Maybe make it a recommendation instead of a requirement?

**Comment by apeltzer** [comment]
I agree that BibTex is kind of one of the more open and standardized ones that most reference managers will just read and import without any modification necessary. Having a CFF is also fine by me, hopefully, the reference managers pick up support for this in the future and then we have it at least present in some pipelines ...?

**Comment by sven1103** [comment]
Sure, lets not make it mandatory for now, until we are 100% sure that we consider it as best practise and there is actually a real benefit :)

**Pull request closed without merging**
